name: Build and deploy app
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy-app:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Add debug information
    env:
      GITHUB_REF: ${{ github.ref }}
      GITHUB_EVENT_NAME: ${{ github.event_name }}
      GITHUB_ACTOR: ${{ github.actor }}
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Debug Info
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "Current branch: $(git branch --show-current)"
          echo "Git status:"
          git status
          echo "Git remote -v:"
          git remote -v
          echo "Git ls-remote:"
          git ls-remote --heads origin
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch all history for all branches and tags
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install modules
        run: yarn --frozen-lockfile
        shell: bash
      - name: Build code
        run: yarn build
        shell: bash
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
