name: Build and lint code
description: Action that installs dependencies, builds and lints the code
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build-and-lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install modules
        run: bun install
      - name: Build code
        run: bun run build
      - name: Lint code
        run: bun run lint
